name: Run tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test upload action
        uses: appswithlove/updraft-deploy-github-action@021749d3669449aa287e05b999d9a4f8c6b73aa0
        with:
          api_key: ${{ secrets.TEST_API_KEY }}
          app_key: ${{ secrets.TEST_APP_KEY }}
          app_path: ./test/test.apk
      - name: Get the output
        run: echo "output ${{ steps.hello.outputs.response_json }}"
